import os
import time
import logging
import threading
from typing import List, Callable
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler, FileModifiedEvent, FileDeletedEvent
import json
import threading
import requests
import shutil
import sys
# Native notifications are now handled via TrayManager callback to ensure stability

from recovery_vault import RecoveryVault
from security_manager import SecurityManager
from process_monitor import ProcessMonitor

def _get_app_root():
    """Detects the physical project directory to prevent 'System32 Drift' on Windows."""
    if getattr(sys, 'frozen', False):
        return os.path.dirname(sys.executable)
    return os.path.dirname(os.path.abspath(__file__))

PROJECT_ROOT = _get_app_root()

logger = logging.getLogger("Scout.Engine")
if not logger.handlers:
    logger.setLevel(logging.INFO)
    ch = logging.StreamHandler()
    ch.setFormatter(logging.Formatter("%(asctime)s | ENGINE | %(levelname)s | %(message)s"))
    logger.addHandler(ch)

class ScoutEventHandler(FileSystemEventHandler):
    """
    Handles file system events generated by watchdog.
    """
    def __init__(self, engine):
        super().__init__()
        self.engine = engine

    def on_modified(self, event):
        if event.is_directory:
            return
        # Filter out changes to our own Vault or Logs
        if ".scout_vault" in event.src_path or "logs" in event.src_path:
            return
            
        abs_path = os.path.abspath(event.src_path)
        if self.engine._is_tracked(abs_path):
            self.engine.handle_modification(abs_path)

    def on_created(self, event):
        if ".scout_vault" in event.src_path or "logs" in event.src_path:
            return
            
        abs_path = os.path.abspath(event.src_path)
        if self.engine._is_tracked(abs_path):
            self.engine.handle_creation(abs_path)

    def on_deleted(self, event):
        abs_path = os.path.abspath(event.src_path)
        if self.engine._is_tracked(abs_path):
            self.engine.handle_deletion(abs_path)


class ScoutEngine:
    def __init__(self):
        # Anchor the vault to the project root to prevent Access Denied in System32
        self.vault = RecoveryVault(os.path.join(PROJECT_ROOT, ".scout_vault"))
        self.security = SecurityManager()
        self.observer = None
        
        # Granular Targets map: abs_path -> {"type": "file"|"folder", "mode": "STRICT"|"MONITORING"}
        self.tracked_targets = {}
        
        # State
        self.is_running = False
        self.global_mode = "MONITORING" # Kept for backward compat fallback
        
        # Callbacks for UI
        self.on_event_callback: Callable[[dict], None] = None
        self.on_notify: Callable[[str, str], None] = None # (title, message)
        self.discord_webhooks = []
        self.toaster = True # Logically enabled by default via TrayManager
        
        # Historical Event Log
        self.history_log = []
        
        self._load_config()
        self._load_history()

    def _get_history_path(self):
        return os.path.join(self.vault.vault_path, "scout_history.json")

    def _save_history(self):
        # Keep last 1000 items
        self.history_log = self.history_log[-1000:]
        try:
            with open(self._get_history_path(), "w") as f:
                json.dump(self.history_log, f)
        except Exception:
            pass

    def _load_history(self):
        path = self._get_history_path()
        if os.path.exists(path):
            try:
                with open(path, "r") as f:
                    self.history_log = json.load(f)
            except Exception:
                self.history_log = []

    def _append_history(self, event_data: dict):
        self.history_log.append(event_data)
        self._save_history()

    def _get_config_path(self):
        return os.path.join(PROJECT_ROOT, "scout_config.json")

    def _save_config(self):
        config = {
            "tracked_targets": self.tracked_targets,
            "discord_webhooks": self.discord_webhooks,
            "global_mode": self.global_mode,
            "vault_path": self.vault.vault_path
        }
        with open(self._get_config_path(), "w") as f:
            json.dump(config, f)

    def _load_config(self):
        config_path = self._get_config_path()
        if os.path.exists(config_path):
            try:
                with open(config_path, "r") as f:
                    config = json.load(f)
                
                v_path = config.get("vault_path", ".scout_vault")
                self.vault = RecoveryVault(v_path)

                self.tracked_targets = config.get("tracked_targets", {})
                self.discord_webhooks = config.get("discord_webhooks", [])
                self.global_mode = config.get("global_mode", "MONITORING")
                
                logger.info(f"Loaded config: Targets={len(self.tracked_targets)}, Vault={v_path}")
            except Exception as e:
                logger.error(f"Failed to load config: {e}")

    def update_vault_path(self, new_path: str):
        """Updates the vault location. Existing data is NOT moved."""
        self.vault = RecoveryVault(new_path)
        self._save_config()
        logger.info(f"Vault path updated to: {new_path}")

    def update_target_mode(self, filepath: str, new_mode: str):
        """Changes the priority of a specific target dynamically."""
        abs_path = os.path.abspath(filepath)
        if abs_path in self.tracked_targets:
            self.tracked_targets[abs_path]["mode"] = new_mode.upper()
            self._apply_locks()
            self._save_config()

    def _apply_locks(self):
        """Applies or removes physical locks based on the targeted dictionary state."""
        # Clean current locks safely? Best to just unlock all and re-lock
        self.security.unlock_all()
        
        for path, info in self.tracked_targets.items():
            if info["mode"] == "STRICT":
                if info["type"] == "file" and os.path.exists(path):
                    self.security.lock_file(path)
                elif info["type"] == "folder" and os.path.exists(path):
                    for root, _, files in os.walk(path):
                        for file in files:
                            self.security.lock_file(os.path.join(root, file))

    def add_target(self, path: str, is_folder: bool = False, mode: str = "MONITORING"):
        abs_path = os.path.abspath(path)
        if not os.path.exists(abs_path):
            return False
            
        self.tracked_targets[abs_path] = {
            "type": "folder" if is_folder else "file",
            "mode": mode.upper()
        }
        
        # Initial scan/baseline for this specific target
        if is_folder:
            for root, _, files in os.walk(abs_path):
                for f in files:
                    self.vault.store_good_version(os.path.join(root, f))
        else:
            self.vault.store_good_version(abs_path)
            
        self._apply_locks()
        self._save_config()
        return True

    def vet_target(self, filepath: str):
        """Administratively approves the current state as the 'Last Known Good'."""
        abs_path = os.path.abspath(filepath)
        if os.path.exists(abs_path):
            success = self.vault.store_good_version(abs_path)
            if success:
                logger.info(f"Administrative Vetting: {abs_path} is now synchronized.")
            return success
        return False

    def _initial_baseline_scan(self):
        """Silently populates the vault for any tracked targets missing a baseline on engine startup."""
        logger.info("Forensic Engine: Performing initial vault synchronization scan...")
        for path, info in self.tracked_targets.items():
            if not os.path.exists(path): continue
            
            if info["type"] == "file":
                if not self.vault.is_tracked(path):
                     self.vault.store_good_version(path)
            else:
                for root, _, files in os.walk(path):
                    for file in files:
                        fpath = os.path.join(root, file)
                        if not self.vault.is_tracked(fpath):
                             self.vault.store_good_version(fpath)
        logger.info("Forensic Engine: Synchronization scan complete.")

    def remove_target(self, path: str):
        abs_path = os.path.abspath(path)
        if abs_path in self.tracked_targets:
            del self.tracked_targets[abs_path]
            self._apply_locks()
            self._save_config()

    def _resolve_target_mode(self, filepath: str) -> str:
        """Finds the most specific mode for a file."""
        abs_path = os.path.abspath(filepath)
        if abs_path in self.tracked_targets:
            return self.tracked_targets[abs_path]["mode"]
            
        longest_match = ""
        resolved_mode = self.global_mode
        for t_path, info in self.tracked_targets.items():
            if info["type"] == "folder" and abs_path.startswith(t_path):
                if len(t_path) > len(longest_match):
                    longest_match = t_path
                    resolved_mode = info["mode"]
        return resolved_mode

    def _is_path_authorized(self, filepath: str) -> bool:
        """Checks if a modification/creation is authorized by an active checkout."""
        abs_path = os.path.abspath(filepath)
        # Check direct target first
        if abs_path in self.tracked_targets:
            return self.tracked_targets[abs_path].get("is_checked_out", False)
            
        # Check parents
        longest_match = ""
        is_checkout = False
        for t_path, info in self.tracked_targets.items():
            if info["type"] == "folder" and abs_path.startswith(t_path):
                if len(t_path) > len(longest_match):
                    longest_match = t_path
                    is_checkout = info.get("is_checked_out", False)
        return is_checkout

    def _is_tracked(self, filepath: str) -> bool:
        abs_path = os.path.abspath(filepath)
        if abs_path in self.tracked_targets:
            return True
        for t_path, info in self.tracked_targets.items():
            if info["type"] == "folder" and abs_path.startswith(t_path):
                return True
        return False

    # --- Event Handlers ---

    def handle_modification(self, filepath: str):
        """Triggered when a tracked file changes."""
        logger.warning(f"File MODIFIED: {filepath}")
        
        # In strict mode, if a file was modified, it means they bypassed the UI checkout
        # Or this was a false positive watchdog event on a locked file.
        # But if it actually changed, we trigger Self-Healing to aggressively revert it.
        # Note: If it's locked by Python, they shouldn't be able to edit it anyway.
        
        # Resolve local mode
        local_mode = self._resolve_target_mode(filepath)

        # 'Check-Out' only exists conceptually when the system is in STRICT mode.
        is_checked_out = (local_mode == "STRICT") and (not self.security.is_locked(filepath))
        
        # Perform Deep Forensics!
        culprit = ProcessMonitor.snapshot_culprit()
        short_name = culprit.get("name", "Unknown Process")
        
        event_data = {
            "type": "MODIFIED",
            "file": filepath,
            "timestamp": time.time(),
            "healed": False,
            "forensics": culprit,
            "diff": "No diff captured."
        }

        # Calculate Diff against Vault Backup before any healing overwrites the file!
        pristine_lines = self.vault.load_pristine_content(filepath)
        
        if not pristine_lines:
            # Lazy Baseline: If we missed the creation event or it was locked, 
            # capture the baseline NOW before we lose the state.
            logger.info(f"Lazy baselining triggered for {os.path.basename(filepath)}")
            self.vault.store_good_version(filepath)
            event_data["message"] = "Initial Baseline Captured (Modification Fallback)"
            event_data["diff"] = "FORENSIC STATUS: Initial baseline copy established during this modification. Subsequent changes will now be fully tracked in side-by-side view."
        elif os.path.exists(filepath):
            try:
                import difflib
                # Use utf-8-sig to automatically handle Byte Order Marks (BOM)
                with open(filepath, "r", encoding="utf-8-sig", errors="replace") as f2:
                    current_lines = f2.readlines()
                
                # Filter binary data (approximate)
                if any("\0" in line for line in current_lines[:10]):
                    event_data["diff"] = "Binary file detected. Cannot perform text comparison."
                else:
                    # Strip newlines for cleaner comparisons
                    p_lines = [l.rstrip("\r\n") for l in pristine_lines]
                    c_lines = [l.rstrip("\r\n") for l in current_lines]
                    
                    matcher = difflib.SequenceMatcher(None, p_lines, c_lines)
                    sync_map = []
                    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
                        if tag == 'equal':
                            for k in range(i2 - i1):
                                sync_map.append({
                                    "left_ln": i1 + k + 1, "left_txt": p_lines[i1+k],
                                    "right_ln": j1 + k + 1, "right_txt": c_lines[j1+k],
                                    "type": "equal"
                                })
                        elif tag == 'replace':
                            # Pair them horizontally for 'changes'
                            max_range = max(i2 - i1, j2 - j1)
                            for k in range(max_range):
                                o_idx = i1 + k if k < (i2 - i1) else None
                                n_idx = j1 + k if k < (j2 - j1) else None
                                sync_map.append({
                                    "left_ln": o_idx + 1 if o_idx is not None else None,
                                    "left_txt": p_lines[o_idx] if o_idx is not None else None,
                                    "right_ln": n_idx + 1 if n_idx is not None else None,
                                    "right_txt": c_lines[n_idx] if n_idx is not None else None,
                                    "type": "change"
                                })
                        elif tag == 'delete':
                            for k in range(i2 - i1):
                                sync_map.append({
                                    "left_ln": i1 + k + 1, "left_txt": p_lines[i1+k],
                                    "right_ln": None, "right_txt": None,
                                    "type": "delete"
                                })
                        elif tag == 'insert':
                            for k in range(j2 - j1):
                                sync_map.append({
                                    "left_ln": None, "left_txt": None,
                                    "right_ln": j1 + k + 1, "right_txt": c_lines[j1+k],
                                    "type": "insert"
                                })
                    
                    if sync_map:
                        event_data["diff"] = sync_map
                    else:
                        event_data["diff"] = "Metadata modification only (no content changes)."
            except Exception as e:
                event_data["diff"] = f"Forensic Error: Could not read file content ({type(e).__name__})."

        if local_mode == "STRICT" and not is_checked_out:
            logger.critical(f"UNAUTHORIZED MODIFICATION in STRICT mode: {filepath}")
            success = self.vault.heal_file(filepath)
            event_data["healed"] = success
            event_data["message"] = f"Self-Healed (Culprit: {short_name})" if success else f"Failed to heal (Culprit: {short_name})"
            logger.info("Attempting to trigger STRICT mode alerts...")
            self._trigger_alerts(f"Unauthorized Modification Stopped & Healed on {os.path.basename(filepath)}", culprit)
        elif local_mode == "STRICT" and is_checked_out:
            logger.info("Modification bypassed - File is temporarily checked out.")
            event_data["message"] = f"File updated during Checkout (By {short_name})"
            # Update the baseline
            self.vault.store_good_version(filepath)
        else:
            logger.info("Attempting to trigger MONITORING mode alerts...")
            event_data["message"] = f"Modification detected (Source: {short_name})"
            self._trigger_alerts(f"Modification Detected on {os.path.basename(filepath)} (Monitoring Mode)", culprit)

        self._append_history(event_data)
        if self.on_event_callback:
            self.on_event_callback(event_data)

    def handle_creation(self, filepath: str):
        """Triggered when a brand new file is created inside a tracked folder."""
        local_mode = self._resolve_target_mode(filepath)
        is_checked_out = self._is_path_authorized(filepath)
        logger.info(f"--- CREATION EVENT --- Path: {filepath} | Mode: {local_mode} | Auth: {is_checked_out}")
        
        event_data = {
            "type": "CREATED",
            "file": filepath,
            "timestamp": time.time(),
            "healed": False
        }

        # 1. KILL-ON-ARRIVAL Enforcement (STRICT & UNAUTHORIZED)
        if local_mode == "STRICT" and not is_checked_out:
            logger.critical(f"UNAUTHORIZED CREATION REJECTED: {filepath}")
            # Aggressive annihilation loop to fight OS file-locks
            success = False
            for i in range(5):
                try:
                    if os.path.exists(filepath):
                        if os.path.isdir(filepath): shutil.rmtree(filepath)
                        else: os.remove(filepath)
                    success = True
                    break
                except Exception as e:
                    logger.warning(f"Kill Attempt {i+1}/5 Failed ({type(e).__name__}): {filepath}")
                    time.sleep(0.3)
            
            if success:
                event_data["healed"] = True
                event_data["message"] = "Self-Healed: Unauthorized Creation Annihilated"
                logger.info(f"Successfully annihilated unauthorized intruder: {filepath}")
            else:
                event_data["message"] = "CRITICAL: FAILED to annihilate unauthorized intruder"
                logger.error(f"POLICE FAILURE: Could not delete intruder {filepath} after 5 attempts.")

            # Snapshot the intruder process immediately
            culprit = ProcessMonitor.snapshot_culprit()
            self._trigger_alerts(f"UNAUTHORIZED CREATION ANNIHILATED: {os.path.basename(filepath)}", culprit)

        # 2. PROCEED with Baseline for Authorized or Monitoring Mode
        else:
            baseline_success = False
            # authorized or monitoring mode allows a grace period for the file to be filled
            for i in range(4):
                time.sleep(0.5)
                if os.path.exists(filepath):
                    if self.vault.store_good_version(filepath):
                        baseline_success = True
                        break

            if local_mode == "STRICT": # must be checked_out to reach here
                self.security.lock_file(filepath)
                event_data["message"] = "Authorized Creation Baseline & Locked (STRICT)"
            else:
                 event_data["message"] = "Creation Detected (Monitoring Mode)"
                 if not os.path.isdir(filepath): self.security.lock_file(filepath)

        self._append_history(event_data)
        if self.on_event_callback:
            self.on_event_callback(event_data)

    def _trigger_alerts(self, message: str, forensics: dict):
        """Dispatches completely asynchronous alerts to Windows OS and Discord."""
        logger.info(f"Entered _trigger_alerts. Toaster available={bool(self.toaster)}, Discord Webhooks={len(self.discord_webhooks)}")
        # 1. Windows Native Toast (Using Stable Tray Callback)
        if self.on_notify:
            try:
                self.on_notify("Scout Security Alert", message)
            except Exception as e:
                logger.error(f"Failed to trigger tray notification: {e}")
                
        # 2. Discord Webhooks
        for webhook in self.discord_webhooks:
            def send_discord(wh_url=webhook):
                payload = {
                    "content": f"🚨 **SCOUT ALERT** 🚨\n{message}",
                    "embeds": [{
                        "title": "Deep Forensic Report",
                        "color": 16724787,
                        "fields": [
                            {"name": "Culprit Executable", "value": forensics.get("name", "Unknown"), "inline": True},
                            {"name": "PID", "value": str(forensics.get("pid", 0)), "inline": True},
                            {"name": "Network Activity", "value": "TRUE 🌐" if forensics.get("network_active") else "False", "inline": True},
                            {"name": "Disk Location", "value": forensics.get("location", "N/A"), "inline": False},
                            {"name": "SHA-256 Hash", "value": f"`{forensics.get('hash', 'N/A')}`", "inline": False}
                        ]
                    }]
                }
                try:
                    logger.info(f"Dispatching Discord Alert to: {wh_url[:30]}...")
                    response = requests.post(wh_url, json=payload, timeout=5)
                    if response.status_code >= 400:
                        logger.error(f"Discord API Error {response.status_code}: {response.text}")
                except Exception as e:
                    logger.error(f"Discord network exception: {e}")
            threading.Thread(target=send_discord, daemon=True).start()

    def handle_deletion(self, filepath: str):
        """Triggered when a tracked file is deleted."""
        logger.warning(f"File DELETED: {filepath}")
        
        event_data = {
            "type": "DELETED",
            "file": filepath,
            "timestamp": time.time(),
            "healed": False
        }
        
        local_mode = self._resolve_target_mode(filepath)
        if local_mode == "STRICT":
            logger.critical(f"UNAUTHORIZED DELETION in STRICT mode: {filepath}")
            # Watchdog sometimes fires before the file handle is fully released by OS.
            time.sleep(0.5) 
            
            # Identify if we are healing a file or a folder
            target_info = self.tracked_targets.get(filepath, {})
            if target_info.get("type") == "folder":
                try:
                    os.makedirs(filepath, exist_ok=True)
                    success = True
                except Exception:
                    success = False
            else:
                success = self.vault.heal_file(filepath)
                # Re-lock the newly healed file
                if success:
                    self.security.lock_file(filepath)
            
            event_data["healed"] = success
            event_data["message"] = "Self-Healed an unauthorized deletion" if success else "Failed to heal deletion"
        else:
            event_data["message"] = "Deletion detected (Monitoring Mode)"

        self._append_history(event_data)
        if self.on_event_callback:
            self.on_event_callback(event_data)

    # --- Core Loop ---
    
    def start(self, directories_to_watch: List[str]):
        """Starts the background monitoring observer."""
        if self.is_running:
            return

        # Perform forensic safety scan before attaching watchers
        self._initial_baseline_scan()

        self.observer = Observer()
        event_handler = ScoutEventHandler(self)
        
        for directory in directories_to_watch:
            if os.path.exists(directory):
                self.observer.schedule(event_handler, path=directory, recursive=True)
                logger.debug(f"Watching directory tree: {directory}")

        self.observer.start()
        self.is_running = True
        logger.info("Scout Engine started.")

    def stop(self):
        """Stops the monitoring observer."""
        if not self.is_running:
            return
            
        self.observer.stop()
        self.observer.join()
        self.security.unlock_all()
        self.is_running = False
        logger.info("Scout Engine stopped.")

    # --- Checkout workflow ---

    def checkout(self, path: str) -> bool:
        logger.info(f"User Checking Out: {path}")
        abs_path = os.path.abspath(path)
        if abs_path in self.tracked_targets:
            self.tracked_targets[abs_path]["is_checked_out"] = True
            
        if os.path.isfile(abs_path):
            self.vault.store_good_version(abs_path)
        
        return self.security.unlock_path(abs_path)

    def checkin(self, path: str) -> bool:
        logger.info(f"User Checking In: {path}")
        abs_path = os.path.abspath(path)
        if abs_path in self.tracked_targets:
            self.tracked_targets[abs_path]["is_checked_out"] = False
            
        if os.path.isfile(abs_path):
            self.vault.store_good_version(abs_path)
            
        if self._resolve_target_mode(abs_path) == "STRICT":
            return self.security.lock_path(abs_path)
        return True

if __name__ == "__main__":
    # Test engine
    engine = ScoutEngine()
    engine.on_event_callback = lambda e: print(f"EVENT: {e}")
    
    # Create test dir and file
    os.makedirs("test_mon", exist_ok=True)
    test_file = os.path.abspath("test_mon/data.json")
    with open(test_file, "w") as f:
        f.write('{"status": "ok"}')
        
    engine.add_file(test_file)
    engine.start(["test_mon"])
    
    print("Testing Monitoring Mode...")
    with open(test_file, "w") as f:
        f.write('{"status": "tampered"}')
    time.sleep(2) # let watchdog catch up
    
    print("\nSwitching to STRICT mode...")
    engine.set_mode("STRICT")
    
    print("Simulating unauthorized edit out-of-band (trying to write circumventing lock)")
    try:
        with open(test_file, "w") as f:
            f.write('{"status": "hacked"}')
    except PermissionError:
        print("Success: Lock prevented OS write.")
        
    print("\nChecking out...")
    engine.checkout(test_file)
    with open(test_file, "w") as f:
        f.write('{"status": "updated_by_user"}')
    print("File edited successfully by user.")
    engine.checkin(test_file)
    
    # Simulated deletion
    print("\nSimulating file deletion in STRICT mode...")
    try:
        # Depending on OS file lock type, deletion might fail immediately, or watchdog fires
        os.remove(test_file)
    except PermissionError:
        print("Success: Lock prevented OS delete.")
        
    engine.stop()
    
    # Cleanup
    if os.path.exists(test_file):
        os.remove(test_file)
    os.rmdir("test_mon")
